---
- name: Setup the kubernetes nodes
  ansible.builtin.import_tasks: setup.yml
  tags: kubernetes_setup

- name: Install kubernetes packages
  ansible.builtin.import_tasks: kubeadm.yml
  tags: kubeadm

- name: Configure master nodes
  ansible.builtin.import_tasks: master.yml
  tags: cluster_formation
  when: kubernetes_role == 'master'

- name: Configure worker nodes
  ansible.builtin.import_tasks: worker.yml
  tags: cluster_formation
  when: kubernetes_role == 'worker'
