---
- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Set sysctl values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
  loop:
    - {name: net.bridge.bridge-nf-call-iptables, value: '1'}
    - {name: net.bridge.bridge-nf-call-ip6tables, value: '1'}
    - {name: net.ipv4.ip_forward, value: '1'}
