---
- name: kubernetes | Deploy metrics server
  kubernetes.core.helm:
    name: metrics-server
    chart_repo_url: https://kubernetes-sigs.github.io/metrics-server
    chart_ref: metrics-server
    chart_version: "{{ metrics_server_chart_version }}"
    release_namespace: metrics-server
    create_namespace: true
    values:
      defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
